# Generated by Django 3.2.6 on 2021-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionparagraph',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summaryparagraph',
            name='details',
            field=models.TextField(),
        ),
    ]
